"""change schema

Revision ID: 3b2f930d9229
Revises: 87c47e72cbe5
Create Date: 2026-02-13 18:09:00.341453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3b2f930d9229'
down_revision: Union[str, Sequence[str], None] = '87c47e72cbe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_embeddings', sa.Column('raw_text', sa.Text(), nullable=False))
    op.alter_column('project_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               nullable=False)
    op.drop_column('project_embeddings', 'raw_text')
    # ### end Alembic commands ###
