"""add_title_id_to_evaluations

Revision ID: 54ebb0087122
Revises: 6e6614eba780
Create Date: 2026-04-18 07:20:29.685716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '54ebb0087122'
down_revision: Union[str, Sequence[str], None] = '6e6614eba780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_evaluations', sa.Column('title_id', sa.Integer(), nullable=True))
    op.alter_column('resume_evaluations', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'resume_evaluations', 'titles', ['title_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume_evaluations', type_='foreignkey')
    op.alter_column('resume_evaluations', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('resume_evaluations', 'title_id')
    # ### end Alembic commands ###
