"""make title_id nullable

Revision ID: 67c1dd5a9020
Revises: f147bed8612b
Create Date: 2026-04-17 07:10:51.579870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '67c1dd5a9020'
down_revision: Union[str, Sequence[str], None] = 'f147bed8612b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_resumes', 'title_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_resumes', 'title_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
