"""add resume_evaluations

Revision ID: 6e6614eba780
Revises: 67c1dd5a9020
Create Date: 2026-04-18 05:24:21.606895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy 


# revision identifiers, used by Alembic.
revision: str = '6e6614eba780'
down_revision: Union[str, Sequence[str], None] = '67c1dd5a9020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['generated_resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_evaluations_id'), 'resume_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_resume_evaluations_user_id'), 'resume_evaluations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_evaluations_user_id'), table_name='resume_evaluations')
    op.drop_index(op.f('ix_resume_evaluations_id'), table_name='resume_evaluations')
    op.drop_table('resume_evaluations')
    # ### end Alembic commands ###
