"""new change

Revision ID: 816238535ede
Revises: 90b7daa5bd53
Create Date: 2026-04-21 06:25:19.063984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '816238535ede'
down_revision: Union[str, Sequence[str], None] = '90b7daa5bd53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_evaluations', sa.Column('profile_gaps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_evaluations', 'profile_gaps')
    # ### end Alembic commands ###
