"""add title description embedding

Revision ID: 8669bfadd33f
Revises: 897315b71082
Create Date: 2026-04-08 06:07:06.707581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '8669bfadd33f'
down_revision: Union[str, Sequence[str], None] = '897315b71082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('description_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('titles', 'description_embedding')
    # ### end Alembic commands ###
