"""updating way of embedding

Revision ID: 87c47e72cbe5
Revises: eb2b4f09c3d7
Create Date: 2026-02-12 18:30:55.777132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '87c47e72cbe5'
down_revision: Union[str, Sequence[str], None] = 'eb2b4f09c3d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('embedding_type', sa.String(length=50), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'embedding_type')
    )
    op.create_index(op.f('ix_project_embeddings_project_id'), 'project_embeddings', ['project_id'], unique=False)
    op.drop_index(op.f('ix_readme_embeddings_project_id'), table_name='readme_embeddings')
    op.drop_table('readme_embeddings')
    op.drop_column('projects', 'readme_markdown')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('readme_markdown', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('readme_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('embedding', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('readme_embeddings_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('readme_embeddings_pkey'))
    )
    op.create_index(op.f('ix_readme_embeddings_project_id'), 'readme_embeddings', ['project_id'], unique=True)
    op.drop_index(op.f('ix_project_embeddings_project_id'), table_name='project_embeddings')
    op.drop_table('project_embeddings')
    # ### end Alembic commands ###
