"""add_ats_fields_to_evaluations

Revision ID: 90b7daa5bd53
Revises: 54ebb0087122
Create Date: 2026-04-21 05:34:00.524533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '90b7daa5bd53'
down_revision: Union[str, Sequence[str], None] = '54ebb0087122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_evaluations', sa.Column('ats_score', sa.Integer(), nullable=True))
    op.add_column('resume_evaluations', sa.Column('ats_feedback', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_evaluations', 'ats_feedback')
    op.drop_column('resume_evaluations', 'ats_score')
    # ### end Alembic commands ###
