"""add education and contact fields

Revision ID: 9ae6a2269abd
Revises: b5d2b3ccbbb2
Create Date: 2026-04-27 17:07:47.717129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy 


# revision identifiers, used by Alembic.
revision: str = '9ae6a2269abd'
down_revision: Union[str, Sequence[str], None] = 'b5d2b3ccbbb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('school', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=False),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('relevant_courses', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_id'), 'education', ['id'], unique=False)
    op.create_index(op.f('ix_education_user_id'), 'education', ['user_id'], unique=False)
    op.add_column('user_profiles', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('github_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'github_url')
    op.drop_column('user_profiles', 'linkedin_url')
    op.drop_column('user_profiles', 'phone')
    op.drop_index(op.f('ix_education_user_id'), table_name='education')
    op.drop_index(op.f('ix_education_id'), table_name='education')
    op.drop_table('education')
    # ### end Alembic commands ###
