"""add cascade delete to resume and revaliation

Revision ID: b5d2b3ccbbb2
Revises: 816238535ede
Create Date: 2026-04-22 11:35:57.734720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b5d2b3ccbbb2'
down_revision: Union[str, Sequence[str], None] = '816238535ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('resume_evaluations_resume_id_fkey'), 'resume_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'resume_evaluations', 'generated_resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume_evaluations', type_='foreignkey')
    op.create_foreign_key(op.f('resume_evaluations_resume_id_fkey'), 'resume_evaluations', 'generated_resumes', ['resume_id'], ['id'])
    # ### end Alembic commands ###
