"""add_generated_resume_table

Revision ID: ec019e1fb7e8
Revises: 0771ad5e050b
Create Date: 2026-04-12 14:16:44.874209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ec019e1fb7e8'
down_revision: Union[str, Sequence[str], None] = '0771ad5e050b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('resume_data', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_resumes_id'), 'generated_resumes', ['id'], unique=False)
    op.create_index(op.f('ix_generated_resumes_user_id'), 'generated_resumes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_resumes_user_id'), table_name='generated_resumes')
    op.drop_index(op.f('ix_generated_resumes_id'), table_name='generated_resumes')
    op.drop_table('generated_resumes')
    # ### end Alembic commands ###
