"""add job description to resume

Revision ID: f0b22cc9a448
Revises: ec019e1fb7e8
Create Date: 2026-04-13 06:39:26.629161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f0b22cc9a448'
down_revision: Union[str, Sequence[str], None] = 'ec019e1fb7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_resumes', sa.Column('job_description', sa.Text(), nullable=True))
    op.add_column('generated_resumes', sa.Column('job_title', sa.String(length=255), nullable=True))
    op.add_column('generated_resumes', sa.Column('company_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_resumes', 'company_name')
    op.drop_column('generated_resumes', 'job_title')
    op.drop_column('generated_resumes', 'job_description')
    # ### end Alembic commands ###
