"""decoupled jobs and resume

Revision ID: f147bed8612b
Revises: f0b22cc9a448
Create Date: 2026-04-16 05:31:01.396299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f147bed8612b'
down_revision: Union[str, Sequence[str], None] = 'f0b22cc9a448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.add_column('generated_resumes', sa.Column('job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'generated_resumes', 'jobs', ['job_id'], ['id'])
    op.drop_column('generated_resumes', 'job_description')
    op.drop_column('generated_resumes', 'company_name')
    op.drop_column('generated_resumes', 'job_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_resumes', sa.Column('job_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('generated_resumes', sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('generated_resumes', sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'generated_resumes', type_='foreignkey')
    op.drop_column('generated_resumes', 'job_id')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
